package bufmgr;

import global.*;

public class Descriptor {
/*Each descriptor is a record with the following fields:
page number, pin_count, dirtybit.
The pin_count field is an integer, page number is a PageId object, and dirtybit is a boolean.
This describes the page that is stored in the corresponding frame.
A page is identified by a page number that is generated by the DB class when the page is allocated, and is unique over all pages in the database.
The PageId type is defined as an integer type in global package.*/
	private int pinCount;
	private PageId pageNumber;
	private boolean dirtyBit;
			
	public Descriptor(PageId pageNumber){
		this.pageNumber = pageNumber;
		dirtyBit = false;
		pinCount = 1;
	}
	int getPinCount(){
		return pinCount;
	}
	PageId getPageNumber(){
		return pageNumber;
	}
	boolean isDirty(){
		return dirtyBit;
	}
	int setDirtyBit(boolean val){
		dirtyBit = val;
		return 1;
	}
	int incrementPinCount(){
		pinCount++;
		return pinCount;
	}
	int decrementPinCount(){
		pinCount--;
		return pinCount;
	}
}
